version: '3.8'

services:
  bizmate-api:
    build:
      context: .
      dockerfile: src/BizMate.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=vuakong;Username=vuakong;Password=vuakongfishing@
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: vuakong-postgres
    restart: always
    environment:
      POSTGRES_USER: vuakong
      POSTGRES_PASSWORD: vuakongfishing@
      POSTGRES_DB: vuakong
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vuakong-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
