//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizMate.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageUtils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessageUtils() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizMate.Application.Resources.MessageUtils", typeof(MessageUtils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} với giá trị {1} đã tồn tại..
        /// </summary>
        internal static string COMMON_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("COMMON_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã bị thay đổi bởi người dùng khác. Vui lòng tải lại và thử lại..
        /// </summary>
        internal static string COMMON_CONCURRENCY_CONFLICT {
            get {
                return ResourceManager.GetString("COMMON_CONCURRENCY_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xung đột dữ liệu: {0}.
        /// </summary>
        internal static string COMMON_CONFLICT {
            get {
                return ResourceManager.GetString("COMMON_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} bị trùng lặp..
        /// </summary>
        internal static string COMMON_DUPLICATE {
            get {
                return ResourceManager.GetString("COMMON_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập tài nguyên này..
        /// </summary>
        internal static string COMMON_FORBIDDEN {
            get {
                return ResourceManager.GetString("COMMON_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} với giá trị {1} không hợp lệ..
        /// </summary>
        internal static string COMMON_INVALID {
            get {
                return ResourceManager.GetString("COMMON_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} không được vượt quá {1} ký tự..
        /// </summary>
        internal static string COMMON_MAX_LENGTH {
            get {
                return ResourceManager.GetString("COMMON_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} phải có ít nhất {1} ký tự..
        /// </summary>
        internal static string COMMON_MIN_LENGTH {
            get {
                return ResourceManager.GetString("COMMON_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} không được để trống..
        /// </summary>
        internal static string COMMON_NOT_EMPTY {
            get {
                return ResourceManager.GetString("COMMON_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} với giá trị {1} không tồn tại..
        /// </summary>
        internal static string COMMON_NOT_EXIST {
            get {
                return ResourceManager.GetString("COMMON_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} là bắt buộc..
        /// </summary>
        internal static string COMMON_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("COMMON_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa được xác thực..
        /// </summary>
        internal static string COMMON_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("COMMON_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi không mong muốn. Vui lòng thử lại sau..
        /// </summary>
        internal static string COMMON_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("COMMON_UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
